backend:
  name: git-gateway
  branch: main

media_folder: "content/images"
public_folder: "/content/images"

media_folder: "static/uploads"    # onde os arquivos ficarão no repositório
public_folder: "/uploads"         # caminho público no site

publish_mode: editorial_workflow  # opcional: permite workflow de revisão

# Se você usa Cloudinary, mantenha media_library; senão pode remover esta seção.
media_library:
  name: cloudinary
  config:
    cloud_name: "dqdbxtlnf"
    upload_preset: "meuparquelins"

collections:
  - name: "avisos"
    label: "Avisos"
    folder: "content/avisos"     # aqui usamos a pasta que você já criou
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Publicado em", name: "date", widget: "datetime", format: "DD/MM/YYYY" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo (exibição)", name: "summary", widget: "text" }
      - { label: "Vídeo (URL YouTube/Vimeo)", name: "video_url", widget: "string", required: false }
      - { label: "Imagens (upload)", name: "image", widget: "image", multiple: true, required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
